site_name: iSAQB glossary
site_description: An extensive glossary of software architecture (and development) terminology. Explains the terms used and referenced in the iSAQB foundation and advanced level curricula.
repo_name: isaqb glossary
repo_url: https://github.com/isaqb-org/glossary

nav:
    - Intro: manuscript/0_intro.md
    - Terms: manuscript/1-terms.md
    - EN-DE: manuscript/42-translations-EN-DE.md
    - DE-EN: manuscript/43-translations-DE-EN.md
    - Categories: manuscript/60-categories.md
    - Resources: manuscript/99-resources.md
    - History: manuscript/revision-history.md
    - Terms:
      - ACL: manuscript/terms/term-acl.md
      - ATAM: manuscript/terms/term-atam.md
      - Abhängigkeit: manuscript/terms/term-dependency.md
      - Abhängigkeits-Umkehr-Prinzip / Dependency Inversion Principle: manuscript/terms/term-dependency-inversion.md
      - Abhängigkeitsinjektion / Dependency Injection (DI): manuscript/terms/term-dependency-injection.md
      - Ablage: manuscript/terms/term-repository.md
      - Abstraktheit: manuscript/terms/term-abstractness.md
      - Abstraktion: manuscript/terms/term-abstraction.md
      - Abwägung: manuscript/terms/term-tradeoff.md
      - Adapter: manuscript/terms/term-adapter.md
      - Aggregat: manuscript/terms/term-aggregate.md
      - Aggregation: manuscript/terms/term-aggregation.md
      - Akkreditierter Schulungsanbieter: manuscript/terms/term-accredited-training-provider.md
      - Akkreditierung: manuscript/terms/term-accreditation.md
      - Akkreditierungsstelle: manuscript/terms/term-accreditation-body.md
      - Allgegenwärtige Sprache: manuscript/terms/term-ubiquitous-language.md
      - Angemessenheit: manuscript/terms/term-appropriateness.md
      - Angriffsbaum: manuscript/terms/term-attack-tree.md
      - Architektur-Framework: manuscript/terms/term-architecture-framework.md
      - Architektur-Qualitätsanforderung: manuscript/terms/term-architecture-quality-requirement.md
      - Architekturbegründung: manuscript/terms/term-architecture-rational.md
      - Architekturbeschreibung: manuscript/terms/term-architecture-description.md
      - Architekturbeschreibungselement: manuscript/terms/term-architecture-description-element.md
      - Architekturbeschreibungssprache: manuscript/terms/term-architecture-description-language.md
      - Architekturbewertung: manuscript/terms/term-architecture-evaluation.md
      - Architekturblickwinkel: manuscript/terms/term-architecture-viewpoint.md
      - Architekturentscheidung: manuscript/terms/term-architectural-decision.md
      - Architekturmodell: manuscript/terms/term-architecture-model.md
      - Architekturmuster: manuscript/terms/term-architecture-pattern.md
      - Architektursicht: manuscript/terms/term-architecture-view.md
      - Architekturstil: manuscript/terms/term-architecture-style.md
      - Architekturziel: manuscript/terms/term-architecture-goal.md
      - Artefakt: manuscript/terms/term-artifact.md
      - Asset: manuscript/terms/term-asset.md
      - Assoziation: manuscript/terms/term-association.md
      - Asymmetrische Kryptographie: manuscript/terms/term-asymmetric-cryptography.md
      - Audit-Arbeitsgruppe:: manuscript/terms/term-audit-working-group.md
      - Authentifizierung: manuscript/terms/term-authentication.md
      - Autorisierung: manuscript/terms/term-authorization.md
      - Azyklischer Abhängigkeitsgrundsatz (ADP): manuscript/terms/term-acyclic-dependencies-principle.md
      - Baustein: manuscript/terms/term-building-block.md
      - Bausteinsicht: manuscript/terms/term-building-block-view.md
      - Begründung: manuscript/terms/term-rationale.md
      - Belang: manuscript/terms/term-concern.md
      - Beobachter / Observer: manuscript/terms/term-observer.md
      - Betrachtetes System: manuscript/terms/term-system-of-interest.md
      - Beziehung: manuscript/terms/term-relationship.md
      - Blackbox: manuscript/terms/term-blackbox.md
      - Bottom-up-Ansatz: manuscript/terms/term-bottom-up.md
      - Broker: manuscript/terms/term-broker.md
      - Brücke: manuscript/terms/term-bridge.md
      - CA: manuscript/terms/term-ca.md
      - CIA-Triade: manuscript/terms/term-cia-triad.md
      - CPSA(R): manuscript/terms/term-cpsa.md
      - CQRS: manuscript/terms/term-cqrs.md
      - Cloud: manuscript/terms/term-cloud.md
      - Common-Closure-Prinzip: manuscript/terms/term-common-closure-principle.md
      - Common-Reuse-Prinzip: manuscript/terms/term-common-reuse-principle.md
      - Dienst: manuscript/terms/term-service.md
      - Dokument: manuscript/terms/term-document.md
      - Dokumentation: manuscript/terms/term-documentation.md
      - Dokumentationserstellung: manuscript/terms/term-documentation-build.md
      - Domain-Driven Design (DDD): manuscript/terms/term-DDD.md
      - Domänenmodell: manuscript/terms/term-domain-model.md
      - Eingebettete Systeme: manuscript/terms/term-economicalness.md
      - Einschränkung: manuscript/terms/term-constraint.md
      - Entität: manuscript/terms/term-entity.md
      - Entropie: manuscript/terms/term-entropy.md
      - Entwurfsmuster: manuscript/terms/term-design-pattern.md
      - Entwurfsprinzip: manuscript/terms/term-design-principle.md
      - Fabrik: manuscript/terms/term-factory.md
      - Fassade: manuscript/terms/term-facade.md
      - Filter: manuscript/terms/term-filter.md
      - Fundamental Modeling Concepts (FMC): manuscript/terms/term-fmc.md
      - Gateway: manuscript/terms/term-gateway.md
      - Geschäftsarchitektur: manuscript/terms/term-business-architecture.md
      - Globale Analyse: manuscript/terms/term-global-analysis.md
      - Heterogener Architekturstil: manuscript/terms/term-heterogeneous-architectural-style.md
      - Heuristik: manuscript/terms/term-heuristic.md
      - Hybrider Architekturstil: manuscript/terms/term-hybrid-architecture-style.md
      - IEEE-1471: manuscript/terms/term-ieee-1471.md
      - ISO 25010: manuscript/terms/term-iso-25010.md
      - ISO 9126: manuscript/terms/term-iso-9126.md
      - Inkrementelle Entwicklung: manuscript/terms/term-incremental-development.md
      - Integrität: manuscript/terms/term-integrity.md
      - Iterative Entwicklung: manuscript/terms/term-iterative-development.md
      - Iterative und inkrementelle Entwicklung: manuscript/terms/term-iterative-and-incremental-development.md
      - Kapselung: manuscript/terms/term-encapsulation.md
      - Kardinalität: manuscript/terms/term-cardinality.md
      - Kerckhoffs\'sches Prinzip: manuscript/terms/term-kerckhoffs-principle.md
      - Knoten (in UML): manuscript/terms/term-node-uml.md
      - Kohäsion: manuscript/terms/term-cohesion.md
      - Kommando: manuscript/terms/term-command.md
      - Komplexität: manuscript/terms/term-complexity.md
      - Komponente: manuscript/terms/term-component.md
      - Komposition: manuscript/terms/term-composition.md
      - Konsistenz: manuscript/terms/term-consistency.md
      - Kontext (eines Systems): manuscript/terms/term-context.md
      - Kontextabgrenzung: manuscript/terms/term-context-view.md
      - Kontextgrenze: manuscript/terms/term-bounded-context.md
      - Konzept: manuscript/terms/term-concept.md
      - Kopplung: manuscript/terms/term-coupling.md
      - Korrespondenz: manuscript/terms/term-correspondence.md
      - Korrespondenzregel: manuscript/terms/term-correspondence-rule.md
      - Laufzeitsicht: manuscript/terms/term-runtime-view.md
      - Liskovsches Substitutionsprinzip: manuscript/terms/term-liskov-substitution-principle.md
      - Mal-/Zeichenprogramm: manuscript/terms/term-drawing-tool.md
      - Microservice: manuscript/terms/term-microservice.md
      - Model-View-Controller: manuscript/terms/term-model-view-controller.md
      - Modellart: manuscript/terms/term-model-kind.md
      - Modellgetriebene Architektur: manuscript/terms/term-model-driven-architecture.md
      - Modellgetriebene Softwareentwicklung / Model-driven software development (MDSD): manuscript/terms/term-model-driven-software-development.md
      - Modellierungswerkzeug: manuscript/terms/term-modeling-tool.md
      - Modul: manuscript/terms/term-module.md
      - Modulare Programmierung: manuscript/terms/term-modular-programming.md
      - Muster: manuscript/terms/term-pattern.md
      - Netz des Vertrauens / Web of Trust: manuscript/terms/term-web-of-trust.md
      - Nichtfunktionale Anforderung: manuscript/terms/term-non-functional-requirement.md
      - Node (Node.js): manuscript/terms/term-node-js.md
      - Notation: manuscript/terms/term-notation.md
      - Nutzungsbeziehung: manuscript/terms/term-uses-relationship.md
      - OWASP: manuscript/terms/term-owasp.md
      - Open-Close-Prinzip (OCP): manuscript/terms/term-open-close-principle.md
      - PKI: manuscript/terms/term-pki.md
      - POSA: manuscript/terms/term-posa.md
      - Packaging-Prinzipien: manuscript/terms/term-package-principles.md
      - Perfect Forward Secrecy / Perfekte vorwärts gerichtete Geheimhaltung: manuscript/terms/term-perfect-forward-secrecy.md
      - Perspektive: manuscript/terms/term-perspective.md
      - Pikachu: manuscript/terms/term-pikachu.md
      - Pipe: manuscript/terms/term-pipe.md
      - Port: manuscript/terms/term-port.md
      - Principal: manuscript/terms/term-principal.md
      - Pseudo-Zufälligkeit: manuscript/terms/term-pseudo-randomness.md
      - Qualitative Bewertung: manuscript/terms/term-qualitative-evaluation.md
      - Qualität: manuscript/terms/term-quality.md
      - Qualitätsanforderung: manuscript/terms/term-quality-requirement.md
      - Qualitätsbaum: manuscript/terms/term-quality-tree.md
      - Qualitätseigenschaft: manuscript/terms/term-quality-characteristic.md
      - Qualitätsmerkmal: manuscript/terms/term-quality-attribute.md
      - Qualitätsmerkmal Adaptierbarkeit: manuscript/terms/term-adaptability-quality-attribute.md
      - Qualitätsmerkmal Analysierbarkeit: manuscript/terms/term-analysability-quality-attribute.md
      - Qualitätsmerkmal Austauschbarkeit: manuscript/terms/term-replaceability-quality-attribute.md
      - Qualitätsmerkmal Authentifizierbarkeit: manuscript/terms/term-authenticity-quality-attribute.md
      - Qualitätsmerkmal Bedienbarkeit: manuscript/terms/term-operability-quality-attribute.md
      - Qualitätsmerkmal Benutzerfreundlichkeit: manuscript/terms/term-usability-quality-attribute.md
      - Qualitätsmerkmal Erkennbarkeit der Brauchbarkeit: manuscript/terms/term-appropriateness-recognizability-quality-attribute.md
      - Qualitätsmerkmal Erlernbarkeit: manuscript/terms/term-learnability-quality-attribute.md
      - Qualitätsmerkmal Fehlertoleranz: manuscript/terms/term-fault-tolerance-quality-attribute.md
      - Qualitätsmerkmal Installierbarkeit: manuscript/terms/term-installability-quality-attribute.md
      - Qualitätsmerkmal Integrität: manuscript/terms/term-integrity-quality-attribute.md
      - Qualitätsmerkmal Interoperabilität: manuscript/terms/term-interoperability-quality-attribute.md
      - Qualitätsmerkmal Kapazität: manuscript/terms/term-capacity-quality-attribute.md
      - Qualitätsmerkmal Koexistenz: manuscript/terms/term-co-existence-quality-attribute.md
      - Qualitätsmerkmal Kompatibilität: manuscript/terms/term-compatibility-quality-attribute.md
      - Qualitätsmerkmal Leistungseffizienz: manuscript/terms/term-performance-efficiency-quality-attribute.md
      - Qualitätsmerkmal Modifizierbarkeit: manuscript/terms/term-modifiability-quality-attribute.md
      - Qualitätsmerkmal Modularität: manuscript/terms/term-modularity-quality-attribute.md
      - Qualitätsmerkmal Nichtabstreitbarkeit: manuscript/terms/term-non-repudiation-quality-attribute.md
      - Qualitätsmerkmal Portierbarkeit: manuscript/terms/term-portability-quality-attribute.md
      - Qualitätsmerkmal Reifegrad: manuscript/terms/term-maturity-quality-attribute.md
      - Qualitätsmerkmal Ressourcenverbrauch: manuscript/terms/term-resource-utilization-quality-attribute.md
      - Qualitätsmerkmal Schutz vor Fehlbedienung: manuscript/terms/term-user-error-protection-quality-attribute.md
      - Qualitätsmerkmal Sicherheit: manuscript/terms/term-security-quality-attribute.md
      - Qualitätsmerkmal Testbarkeit: manuscript/terms/term-testability-quality-attribute.md
      - Qualitätsmerkmal Verantwortlichkeit: manuscript/terms/term-accountability-quality-attribute.md
      - Qualitätsmerkmal Verfügbarkeit: manuscript/terms/term-availability-quality-attribute.md
      - Qualitätsmerkmal Vertraulichkeit: manuscript/terms/term-confidentiality-quality-attribute.md
      - Qualitätsmerkmal Wartbarkeit: manuscript/terms/term-maintainability-quality-attribute.md
      - Qualitätsmerkmal Wiederherstellbarkeit: manuscript/terms/term-recoverability-quality-attribute.md
      - Qualitätsmerkmal Wiederverwendbarkeit: manuscript/terms/term-reusability-quality-attribute.md
      - Qualitätsmerkmal Zeitverhalten: manuscript/terms/term-time-behaviour-quality-attribute.md
      - Qualitätsmerkmal Zugänglichkeit: manuscript/terms/term-accessibility-quality-attribute.md
      - Qualitätsmerkmal Zuverlässigkeit: manuscript/terms/term-reliability-quality-attribute.md
      - Qualitätsmerkmal funktionale Angemessenheit: manuscript/terms/term-functional-appropriateness-quality-attribute.md
      - Qualitätsmerkmal funktionale Eignung: manuscript/terms/term-functional-suitability-quality-attribute.md
      - Qualitätsmerkmal funktionale Korrektheit: manuscript/terms/term-functional-correctness-quality-attribute.md
      - Qualitätsmerkmal funktionale Vollständigkeit: manuscript/terms/term-functional-completeness-quality-attribute.md
      - Qualitätsmerkmal Ästhetik der Benutzeroberfläche: manuscript/terms/term-user-interface-aesthetics-quality-attribute.md
      - Qualitätsmodell: manuscript/terms/term-quality-model.md
      - Quantitative Bewertung: manuscript/terms/term-quantative-evaluation.md
      - Querschnittsbelang: manuscript/terms/term-cross-cutting-concern.md
      - Querschnittskonzept: manuscript/terms/term-cross-cutting-concept.md
      - RBAC (Role Based Access Control / Rollenbasierte Zugriffskontrolle): manuscript/terms/term-rbac.md
      - RM/ODP: manuscript/terms/term-rm-odp.md
      - Redesign: manuscript/terms/term-redesign.md
      - Refactoring: manuscript/terms/term-refactoring.md
      - Registry: manuscript/terms/term-registry.md
      - Reuse-Release-Equivalence-Prinzip: manuscript/terms/term-reuse-release-equivalence-principle.md
      - Round-Trip-Engineering: manuscript/terms/term-round-trip-engineering.md
      - Ruby: manuscript/terms/term-ruby.md
      - S.O.L.I.D.-Prinzipien: manuscript/terms/term-solid-principles.md
      - SCS (Self Contained System): manuscript/terms/term-self-contained-system.md
      - SDL: manuscript/terms/term-sdl.md
      - Schicht: manuscript/terms/term-layer.md
      - Schnittstelle: manuscript/terms/term-interface.md
      - Schnittstellenaufteilungsprinzip (ISP): manuscript/terms/term-interface-segregation-principle.md
      - Schulungsanbieter: manuscript/terms/term-training-provider.md
      - Schulungsleiter: manuscript/terms/term-trainer.md
      - Schulungslevel: manuscript/terms/term-training-level.md
      - Schutzziele: manuscript/terms/term-security-goals.md
      - Sensitivitätspunkt: manuscript/terms/term-sensitivity-point.md
      - Separation of concern (SoC): manuscript/terms/term-separation-of-concern.md
      - Sequenzdiagramm: manuscript/terms/term-sequence-diagram.md
      - Service (DDD): manuscript/terms/term-service-ddd.md
      - Sicht: manuscript/terms/term-view.md
      - Single-Responsibility-Prinzip (SRP): manuscript/terms/term-single-responsibility-principle.md
      - Singleton: manuscript/terms/term-singleton.md
      - Softwarearchitektur:: manuscript/terms/term-software-architecture.md
      - Softwarequalität: manuscript/terms/term-software-quality.md
      - Stable-Abstractions-Prinzip: manuscript/terms/term-stable-abstractions-principle.md
      - Stable-Dependencies-Prinzip: manuscript/terms/term-stable-dependencies-principle.md
      - Stakeholder: manuscript/terms/term-stakeholder.md
      - Stellvertreter / Proxy: manuscript/terms/term-proxy.md
      - Struktur: manuscript/terms/term-structure.md
      - Strukturelement: manuscript/terms/term-structural-element.md
      - Symmetrische Kryptographie: manuscript/terms/term-symmetric-cryptography.md
      - System: manuscript/terms/term-system.md
      - Szenario: manuscript/terms/term-scenario.md
      - TLS: manuscript/terms/term-tls.md
      - TOGAF: manuscript/terms/term-togaf.md
      - Template (zur Dokumentation): manuscript/terms/term-template.md
      - Top-Down: manuscript/terms/term-top-down.md
      - Umgebung: manuscript/terms/term-environment.md
      - Unified Modeling Language / Vereinheitlichte Modellierungssprache (UML): manuscript/terms/term-uml.md
      - Unternehmens-IT-Architektur: manuscript/terms/term-enterprise-it-architecture.md
      - Verbergen von Informationen: manuscript/terms/term-information-hiding.md
      - Verfolgbarkeit: manuscript/terms/term-traceability.md
      - Verfügbarkeit: manuscript/terms/term-availability.md
      - Verteilung: manuscript/terms/term-deployment.md
      - Verteilungssicht: manuscript/terms/term-deployment-view.md
      - Vertraulichkeit: manuscript/terms/term-confidentiality.md
      - Wasserfall-Entwicklung: manuscript/terms/term-waterfall-development.md
      - Werkzeug- und Materialansatz: manuscript/terms/term-tools-and-material-approach.md
      - Wertobjekt: manuscript/terms/term-value-object.md
      - Whitebox: manuscript/terms/term-whitebox.md
      - Workflow-Management-System (WFMS): manuscript/terms/term-workflow-management-system.md
      - Wrapper: manuscript/terms/term-wrapper.md
      - Zerlegung: manuscript/terms/term-decomposition.md
      - Zertifizierungsprogramm: manuscript/terms/term-certification-program.md
      - Zufälligkeit: manuscript/terms/term-randomness.md
      - Zyklomatische Komplexität: manuscript/terms/term-cyclomatic-complexity.md
      - arc42: manuscript/terms/term-arc42.md
      - iSAQB: manuscript/terms/term-isaqb.md
      - Architectural Tactic: manuscript/terms/term-architectural-tactic.md
      - Architecture: manuscript/terms/term-architecture.md
      - Architecture Objective: manuscript/terms/term-architecture-objective.md
      - Assessment: manuscript/terms/term-assessment.md
      - C4 Model: manuscript/terms/term-c4-model.md
      - Conceptual Integrity: manuscript/terms/term-conceptual-integrity.md
      - Curriculum: manuscript/terms/term-curriculum.md
      - Design Rationale: manuscript/terms/term-design-rationale.md
      - Embedded System: manuscript/terms/term-embedded-systems.md
      - Fitness Function: manuscript/terms/term-fitness-function.md
      - Function Signature: manuscript/terms/term-function-signature.md
      - Latency: manuscript/terms/term-latency.md
      - MFA: manuscript/terms/term-MFA.md
      - Risk: manuscript/terms/term-risk.md
      - Signature: manuscript/terms/term-signature.md
      - Temporal Coupling: manuscript/terms/term-temporal-coupling.md
      - Unit Test: manuscript/terms/term-unit-test.md

theme:
    name: material
    palette:
      primary: 'blue'
      accent: 'red'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
# - codehilite
  - toc:
      permalink: True
edit_uri: ""
