site_name: iSAQB glossary
site_description: An extensive glossary of software architecture (and development) terminology. Explains the terms used and referenced in the iSAQB foundation and advanced level curricula.
repo_name: isaqb glossary
repo_url: https://github.com/isaqb-org/glossary

nav:
    - Intro: manuscript/0_intro.md
    - Terms: manuscript/1-terms.md
    - EN-DE: manuscript/42-translations-EN-DE.md
    - DE-EN: manuscript/43-translations-DE-EN.md
    - Categories: manuscript/60-categories.md
    - Resources: manuscript/99-resources.md
    - History: manuscript/revision-history.md
    - Terms:
      - DDD: manuscript/terms/term-DDD.md



theme:
    name: material
    palette:
      primary: 'blue'
      accent: 'red'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
# - codehilite
  - toc:
      permalink: True
edit_uri: ""
